CC = gcc
CFLAGS = -g
OBJECTS = main.o dynArrays.o reader.o notebook.o command.o
HEADERS = reader.h dynArrays.h notebook.h command.h  

program: 
	$(CC) -o note -g main.c notebook.c reader.c command.c dynArrays.c -lm